# Set a sane configuration for this WordPress instance

- include_vars: wp-destructive.yml
- include_vars: symlink-vars.yml

- assert:
    that:
      - wp_can.configure or ansible_check_mode

# It never hurts to have a working "wp" symlink at the top level of
# the WordPress site, so do this first:
- name: "“Main” symlink to /wp"
  tags: symlink
  check_mode: no   # Does The Right Thing under ansible-playbook --check
  when: wp_ensure_symlink_version is defined
  shell:
    cmd: |
      set -e -x
      cd "{{ wp_dir }}"
      target="/wp/{{ wp_ensure_symlink_version }}"
      [ "$(readlink "wp" 2>/dev/null || true)" = "$target" ] && return 0

      echo SYMLINK_CHANGED
      {% if ansible_check_mode %}
      echo >&2 "$PWD/wp points to $(readlink "wp"); $target expected"
      {% else %}
      tmpdir="$(mktemp -d ./tmpnewsymlink-XXXXXX)"
      (cd "$tmpdir"; ln -s "$target" wp)
      mv "$tmpdir"/wp .
      rmdir "$tmpdir"
      {% endif %}
  register: _main_symlink_script
  changed_when: >
    "SYMLINK_CHANGED" in _main_symlink_script.stdout

- name: "Invalidate serving pods' NFS cache entries for the main symlink"
  tags: symlink
  when: >
    _main_symlink_script is changed
  local_action:
    module: shell
    executable: bash
    cmd: |
      set -o pipefail
      set -e -x
      for pod in $(oc get pods -n "{{ openshift_namespace }}" -o json \
                   | jq -r \
                       '.items
                        | map(select(
                            "'"{{ openshift_dc }}"'" ==
                            .metadata.annotations["openshift.io/deployment-config.name"]
                             ))
                        | map(.metadata.name) | .[]')
      do
        oc exec -n "{{ openshift_namespace }}" -c "{{ openshift_container_name }}" -it $pod -- ls -l "{{ wp_dir }}"
      done

- name: WP_CONTENT_DIR line in wp-config.php
  lineinfile:
    state: "{{ 'present' if wp_is_symlinked else 'absent' }}"
    path: "{{ wp_dir }}/wp-config.php"
    insertafter: table_prefix
    regexp: WP_CONTENT_DIR
    line: |
      define('WP_CONTENT_DIR', '{{ wp_dir }}/wp-content');

- name: "Set up index.php"
  copy:
    dest: "{{ wp_dir }}/index.php"
    content: "{{ lookup('template', 'wordpress-index.php') }}"

- name: Detect whether a WordPress database update is needed
  shell: '{{ wp_cli_command }} core update-db --dry-run'
  changed_when: false
  register: _wp_core_db_update_dry_run

- name: Do WordPress database update
  shell:
    cmd: |
      {{ wp_cli_command }} core update-db
  when: >
    "already" not in _wp_core_db_update_dry_run.stdout

- name: Check whether ping_sites is set
  command: "{{ wp_cli_command }} option get ping_sites"
  changed_when: false
  register: _wp_config_ping_sites

- name: Unset ping_sites
  command: "{{ wp_cli_command }} option set ping_sites ''"
  when: >
    _wp_config_ping_sites is not skipped
    and (_wp_config_ping_sites.stdout != '')
