# Set a sane configuration for this WordPress instance

- include_vars: wp-destructive.yml
- include_vars: symlink-vars.yml

- assert:
    that:
      - wp_can.configure or ansible_check_mode

- name: WP_CONTENT_DIR line in wp-config.php
  lineinfile:
    state: "{{ 'present' if wp_is_symlinked else 'absent' }}"
    path: "{{ wp_dir }}/wp-config.php"
    insertafter: table_prefix
    regexp: WP_CONTENT_DIR
    line: |
      define('WP_CONTENT_DIR', '{{ wp_dir }}/wp-content');

- name: "Set up index.php"
  copy:
    dest: "{{ wp_dir }}/index.php"
    content: "{{ lookup('template', 'wordpress-index.php') }}"

- name: Detect whether a WordPress database update is needed
  shell: '{{ wp_cli_command }} core update-db --dry-run'
  changed_when: false
  register: _wp_core_db_update_dry_run

- name: Do WordPress database update
  shell:
    cmd: |
      {{ wp_cli_command }} core update-db
  when: >
    "already" not in _wp_core_db_update_dry_run.stdout

- name: Check whether ping_sites is set
  command: "{{ wp_cli_command }} option get ping_sites"
  changed_when: false
  register: _wp_config_ping_sites

- name: Unset ping_sites
  command: "{{ wp_cli_command }} option set ping_sites ''"
  when: >
    _wp_config_ping_sites is not skipped
    and (_wp_config_ping_sites.stdout != '')
